extract_utils: Allow prebuilt_apex to override modules
AOSP packages expect Google modules to use AOSP names.

error: packages/modules/RuntimeI18n/apex/Android.bp:67:1: dependency "art-bootclasspath-fragment" of "i18n-bootclasspath-fragment" missing variant:
os:android,arch:common,apex:com.android.art
available variants:
os:android,arch:common

Change-Id: I88417a8e3bcb077a62e98e463ba8e2f685dc947b