extract_utils: Allow prebuilt_apex to set apex_name
The Android build system expects Google modules
to use the same apex_name as AOSP.

error: packages/modules/RuntimeI18n/apex/Android.bp:67:1: dependency "art-bootclasspath-fragment" of "i18n-bootclasspath-fragment" missing variant:
os:android,arch:common,apex:com.android.art
available variants:
os:android,arch:common

Change-Id: Iaf123c7123d8326c71f2baeb2d12dbdda3729539